name: Java CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11      - name: Run Tests
        if: github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'
        id: tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: check
      - name: Run Build
        if: github.event_name == 'push'
        id: build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
      - name: Publish Test Report
        if: steps.build.outcome == 'failure' || steps.tests.outcome == 'failure'
        uses: scacap/action-surefire-report@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          report_paths: '**/build/test-results/test/TEST-*.xml'